apiVersion: v1
kind: Service

metadata:
  name: report-service
  namespace: school

spec:
  type: ClusterIP
  selector:
    app: report

  ports:
    - name: http
      port: 7200
      targetPort: 7200