apiVersion: v1
kind: Service

metadata:
  name: teaching-service
  namespace: school

spec:
  type: ClusterIP
  selector:
    app: teaching

  ports:
    - name: http
      port: 7101
      targetPort: 7101