server:
  port: 7001
  servlet:
    context-path: /

spring:
  application:
    name: teacher

  main:
    #允许使用相同的服务名
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

rpc:
  report: report-service.school:7200

feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 100
    connection-timeout: 2

  okhttp:
    enabled: true