apiVersion: v1
kind: Service

metadata:
  name: student-service
  namespace: school

spec:
  type: ClusterIP
  selector:
    app: student

  ports:
    - name: http
      port: 7000
      targetPort: 7000