server:
  port: 7000
  servlet:
    context-path: /

spring:
  application:
    name: student

  main:
    #允许使用相同的服务名
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

rpc:
  user: user-service.school:7300
  classGrade: classgrade-service.school:7100
  book: book-service.school:7201
  teaching: teaching-service.school:7101

feign:
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 100
    connection-timeout: 2

  okhttp:
    enabled: true