apiVersion: v1
kind: Service

metadata:
  name: message-service
  namespace: school

spec:
  type: ClusterIP
  selector:
    app: message

  ports:
    - name: http
      port: 7301
      targetPort: 7301