#添加istio入口
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: httpbin-gateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway

  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "istio-test.com"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-gateway-vs
  namespace: school
spec:
  hosts:
    - "istio-test.com"
  gateways:
    - httpbin-gateway.istio-system
  http:
    - match:
        - uri:
            prefix: /class

      route:
        - destination:
            port:
              number: 7000
            host: student-service

    - match:
        - uri:
            prefix: /auth

      route:
        - destination:
            port:
              number: 8000
            host: auth-service